### ISSUE TITLE
Edge compatibility

### ISSUE THREAD

**Issue by kiraarghy** [FormidableLabs/runpkg#82] opened 2019-06-04 09:26 UTC
Currently Edge doesn't load the page. 

Checking it on BrowserStack doesn't result in any clear error messages. 

Need to investigate further.

**Comment by VirtualDOMinic** [comment] 2019-06-04 09:48
Had a look on Edge just now. The error/warning I'm getting is:
`HTML1500: Tag cannot be self-closing. Use an explicit closing tag.`

It looks like this is caused by the `svg` paths e.g. `<path class="corner-bg" fill="#E8E8E8" d="M0 52V0h52v52z" />` and beyond...


I haven't read these yet, but these two links seem helpful:
- http://stuntbox.com/blog/2013/06/bulletproof-inline-svg/ 
- https://stackoverflow.com/questions/28948210/how-to-avoid-html1500-tag-cannot-be-self-closing-warning-in-ie-when-using-embedd

I'm not sure if changing to `<path ...></path>` will still work fine while making Edge happy...

**Comment by kiraarghy** [comment] 2019-06-04 09:50
Hmmm I'll have a look at putting a fix together for this, this morning.

**Comment by kiraarghy** [comment] 2019-06-04 10:41
Nope closing tags haven't fixed it, currently still open!

**Comment by BrittanyIRL** [comment] 2019-06-09 22:13
Did some poking around, maybe these are things you already came across but just incase - 

The console errors I'm getting are different from the one listed above but echoing what @VirtualDOMinic mentioned that more will crop up because edge is so cutting edge.  

`SCRIPT5009: 'EventSource' is not defined` is for server sent events - the edge team has had an open ticket to make this update for a few years. https://wpdev.uservoice.com/forums/257854-project-spartan-platform/suggestions/6263825-server-sent-events-eventsource

`SCRIPT5022: Expected identifier, string or number` is probably from destructuring objects. https://stackoverflow.com/questions/53628191/edge-script1028-expected-identifier-string-or-number

I'm not familiar enough with this codebase to go poking through and updating how you're compiling so I thought I'd just leave the research I came across.

It's a bummer about the `EventSource` it seems like something that they should probably have fixed already.

**Comment by lukejacksonn** [comment] 2019-12-03 17:01
Did anyone ever get to the bottom of this, or tried with the most recent release to see if issues still occur?

**Comment by kylecesmat** [comment] 2020-09-21 18:53
Testing this in the latest (Version 85.0.564.60) of Edge for Mac and it appears to be working without any runtime errors. Note this is the modern version that ships with chromium core.

[Looking at this usage table](https://caniuse.com/usage-table), it appears only `~0.65%` of traffic would fall within the legacy/non-chromium version - And it's likely that number is much lower amongst "developer" users who would use this tool. 

My recommendation would be to close this as a WONTFIX, as the version of Edge this was occurring under is no longer relevant.

**Closed by kylecesmat** 2020-09-21 18:53 UTC
Labels: bug, help wanted
