### ISSUE TITLE
Syntax highlighting is broken with (nested?) template strings

### ISSUE THREAD

**Issue by DjebbZ** [FormidableLabs/runpkg#66] opened 2019-05-13 15:23 UTC
Hello,

I've just seen the announcement on Twitter, congrats!

I've tried looking at the latest sveltejs, and at approximately 1/3 of the file all the code is highlighted as a string. 

Offending file: https://runpkg.com/?svelte@3.3.0/internal.js

Offending code:

``` javascript
const animation = node.style.animation || '';
node.style.animation = `${animation ? `${animation}, ` : ``}${name} ${duration}ms linear ${delay}ms 1 both`; 
// starting from the column everything is highlighted as a string
```

This is a very raw bug report, I literally heard about runpkg 5 minutes ago, so I made no further investigation. I hope this helps uncover a real bug somewhere!

End of report!

**Comment by VirtualDOMinic** [comment] 2019-05-13 15:58
Interesting! It looks to me like the ```` empty template string is the cause. Thanks for bringing it up

**Comment by DjebbZ** [comment] 2019-05-13 16:02
You're welcome!

**Comment by VirtualDOMinic** [comment] 2019-05-14 11:12
Update: I think you're right, actually: it looks like the regex from `prism` (the package we're using for syntax highlighting) doesn't account for nested template literals in the quoted regex below, as it appears to check for the first closing curly bracket `\${[^}]+}` that it finds. 

```js 
/`(?:\\[\s\S]|\${[^}]+}|[^\\`])*`/
```

This isn't top of the priorities, but - in time - I'll definitely have a look to see if there's an elegant way to fix it.

**Comment by VirtualDOMinic** [comment] 2019-05-14 11:31
Ok, I lied. I think I have a fix! 

Please see the relevant PR https://github.com/FormidableLabs/runpkg/pull/68 

Would love for you to try it out and give feedback @DjebbZ . See the link to view the branch in the comment by `now bot` on that PR

**Closed** 2019-05-14 15:07 UTC

**Comment by DjebbZ** [comment] 2019-05-15 07:23
Wow, that was fast. I don't know another package that has nested string literals, I really stumbled upon this pattern by chance. Looks good on Svelte (I know it's a bit late since you already merged).

Happy to have been helpful to the project. Cheers!
