### ISSUE TITLE
Line numbers in the code viewer

### ISSUE THREAD

**Issue by calebmer** [FormidableLabs/runpkg#103] opened 2019-06-07 16:52 UTC
I use https://runpkg.com sometimes to debug stack traces that point to my `node_modules` when I don’t have access to the actual `node_modules` folder. It would be really helpful if I could see line numbers in the code viewer.

Other related features I’d really appreciate:

- Jump to line/column. I’d love to type in https://runpkg.com/follow-redirects/index.js:158:24 which comes from a stack trace and jump right there.
- URL to share a specific line number or range of line numbers. When I’m debugging an issue for others I can then link to the actual problem code from runkg.com

**Comment by VirtualDOMinic** [comment] 2019-06-10 09:31
Glad to hear you're finding runkpg useful!

This issue is essentially a duplicate of #44 , but includes more detail, so I'll close that one in favour of this.

It's definitely a feature we're looking into, but we haven't yet assessed how feasible it is. I'll update this issue with more information as things progress.

**Comment by VirtualDOMinic** [comment] 2019-06-10 10:46
For a bit of fun, in the meantime you could do something like this to show line numbers:
```js 
document.querySelector("pre").innerHTML = 
document.querySelector("pre")
  .innerHTML.split(/\n/)
  .map((x, i) => `<span class="token line-number L${i+1}">${i+1}\t</span>` + x)
  .join("\n")
```

...and if you wanted a function to then do the scrolling for you, you could do something like this, where `158` is the line number you want.
```js
(function(lineNumber){
  document.querySelector(`.L${lineNumber}`).scrollIntoView();
  document.querySelector("article").scrollBy(0, -55);
})(158)
```

Definitely not proposing this as a long-term solution, but the snippet for showing line numbers might prove at least moderately useful for now

**Comment by lukejacksonn** [comment] 2019-11-08 14:33
I swear that react-simple-editor can render line numbers by config 🤔

**Comment by lukejacksonn** [comment] 2019-11-19 13:33
Line numbers have been added as part of https://github.com/FormidableLabs/runpkg/pull/139. There is still a bit of work to be done:

- Multi line highlight (if we think this is useful)
- Scrolling to highlighted line (most certainly useful)

So we are on the case @calebmer, thanks for the suggestion!

**Comment by lukejacksonn** [comment] 2019-11-23 00:01
This is done now, thanks to @alex-saunders  🎉

**Closed by lukejacksonn** 2019-11-23 00:01 UTC
Labels: enhancement
